### ISSUE TITLE
Questions for Yeray Díaz Díaz

### ISSUE THREAD

**Issue by ebonat** [yeraydiazdiaz/asyncio-ftwpd#1]
Let me know best email to contact you!

Thank you for your time,

Ernest Bonat, Ph.D.
Senior Software Engineer
Senior Data Scientist

**Comment by yeraydiazdiaz** [comment]
Hi Ernest,

I'm sorry but I currently don't have time to answer questions in a timely manner, I suggest you post your questions in [StackOverflow](http://stackoverflow.com/questions/tagged/python-asyncio) and tag it with `python-asyncio`, you'll have a much better chance of getting a quick response.

Best regards,
Yera

**Comment by ebonat** [comment]
Hi Yeray

Thank you for letting me know!

Thanks

Ernest Bonat, Ph.D.
Senior Software Engineer
Senior Data Scientist

*The content of this email is confidential. It is intended only for the use
of the persons named above. If you are not the intended recipient, you are
hereby notified that any review, dissemination, distribution or duplication
of this communication is strictly prohibited. If you are not the intended
recipient, please contact the sender by reply email and destroy all copies
of the original message.*
